#!/bin/sh

mkdir -p "/var/service"
mkdir -p "/run/runit"

mkdir -p /dev/pts
mount -t devpts none /dev/pts

SHELL="/bin/sh"
echo "$SHELL" >> "/etc/shells"

USER="user"
PASSWORD="password"
/usr/bin/adduser -s "$SHELL" -D "$USER"
echo -e "$PASSWORD\n$PASSWORD" | /usr/sbin/passwd "$USER"

echo "$USER ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/user

for f in /etc/init.d/rcS.d/*
do
	[ -x "$f" ] && $f
done
