---
name: CI

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            xbps_arch: aarch64-musl
            repo: https://repo-default.voidlinux.org/current/aarch64
          - arch: x86_64
            xbps_arch: x86_64-musl
            repo: https://repo-default.voidlinux.org/current/musl

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a
        # v3.3.0

      - name: Set up Docker Buildx
        uses: >-
          docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca
        # v3.9.0

      - name: Build and export
        uses: >-
          docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        # v6.15.0
        with:
          context: .
          file: docker/Dockerfile
          target: export-initramfs
          build-args: |
            ARCH=${{ matrix.arch }}
            XBPS_ARCH=${{ matrix.xbps_arch }}
            REPO=${{ matrix.repo }}
          outputs: type=local,dest=dist

      - name: Upload artifact
        uses: >-
          actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        # v4.6.1
        with:
          name: initramfs-${{ matrix.arch }}
          path: dist/initramfs.cpio.gz
